### ISSUE TITLE
Create a model.py file

### ISSUE THREAD

**Issue by JiayuanHu** [NYU-Wishlists/wishlists#10]
**As a** microservice developer
**I need** a model file
**So that** all model definitions of resources can be held clearly.

**Assumptions:**
- Our microservice will mostly base on these models

**Acceptance Criteria:**
```
Given model.py
When access any model in the file
Then all the features can be retrieved
```

**Comment by JiayuanHu** [comment]
I'm giving this story 8 points,  is that OK?

**Comment by minhlai** [comment]
***Model Prototype***

Wishlist
- PK: Wishlist ID
- Wishlist Name
- User name

Wishlist Entry
- PK: Entry ID
- FK: User Name
- Item Name
- Quantity
- Price

**Comment by JiayuanHu** [comment]
Why is the Quantity feature?
