### ISSUE TITLE
Add Dev Stage

### ISSUE THREAD

**Issue by minhlai** [NYU-Wishlists/wishlists#115]
**As a** developer
**I need** to a dev deployment stage in my pipeline
**So that** I can automatically deploy to my dev space as soon as my merge passes tests.

**Assumptions:**
* build stage has passed with no errors

**Acceptance Criteria:**
```
Given my app has passed the build stage with no errors
Then it should automatically deploy to my dev space and be able to be accessed,
```

**Comment by dyk303** [comment]
Dev stage added
