### ISSUE TITLE
Delete all wishlists of a user

### ISSUE THREAD

**Issue by JiayuanHu** [NYU-Wishlists/wishlists#38]
**As a** customer
**I need** an action based call
**So that** I can delete all wishlists of a user

**Assumptions:**
* rest call should include data which indicates which user's wishlists to delete 

**Acceptance Criteria:**
```
Given a user id
When call PUT /wishlists/<int:user_id>/deleteall
Then return empty wishlist and HTTP_200_OK
```

**Comment by okatz18** [comment]
should be:
When call PUT /wishlists/<string:user_name>/deleteall
