### ISSUE TITLE
Create a Python Flask Cloud Foundry application in IBM Cloud

### ISSUE THREAD

**Issue by minhlai** [NYU-Wishlists/wishlists#46]
**As a** ... Product Owner
**I need** ... a cloud microservice for wishlists
**So that** ... my customers can save their products.

**Assumptions:**
* ... resource name must be singular
* ... resource name must be prefixed by "nyu-" and suffixed by "-servicef18"

**Acceptance Criteria:**
```
Given ... an IBM cloud account
When ... I check the IBM cloud organization
Then ... I should see our application named, "nyu-wishlist-servicef18 and our URL should be nyu-
wishlist-service-f18.mybluemix.net

**Comment by okatz18** [comment]
Problem pushing and starting to instance 
`0 of 1 instances running, 1 crashed
FAILED
Error restarting application: Start unsuccessful
`
