### ISSUE TITLE
Refactor get wishlists method and add swagger doc

### ISSUE THREAD

**Issue by minhlai** [NYU-Wishlists/wishlists#62]
**As a** developer 
**I need** to refactor /Get/ method and add swagger api doc
**So that** the app works on the cloud 

**Assumptions:**
* The /Get/ method that passed all the tests

**Acceptance Criteria:**
```
When the /Get/ method is called 
Then it should work the same as it did before refactoring with Swagger
```

**Comment by JiayuanHu** [comment]
get, update, delete should be done by one person for  /wishlists/{id}
