### ISSUE TITLE
Refactor add wishlist method and add swagger doc

### ISSUE THREAD

**Issue by minhlai** [NYU-Wishlists/wishlists#74]
**As a** customer 
**I need** a rest api to add a wishlist and add swagger api doc
**So that**  I can see the documentation and add a wishlist

**Acceptance Criteria:**
use restplus to automatically generate swagger doc

```
Given the running service
When call POST /wishlists/
Then return the wishlist created and HTTP response 201
```

**Comment by JiayuanHu** [comment]
implementing
