### ISSUE TITLE
Refactor list wishlists method and add swagger doc

### ISSUE THREAD

**Issue by minhlai** [NYU-Wishlists/wishlists#75]
**As a** customer 
**I need** a rest api to get all wishlists and swagger doc
**So that** I can see the documentation and all the wishlists

**Assumptions:**
use restplus to automatically generate swagger doc

**Acceptance Criteria:**
```
Given the running service
When call GET /wishlists/
Then return all the wishlists and 200
```

**Comment by JiayuanHu** [comment]
implementing
